---
title: CV
format:
  quarto-cv-pdf: default
author: Ches Thurber
department: "Department of Political Science"
school: "School of Public and Global Affairs"
institution: "Northern Illinois University"
date: last-modified
phone: (815) 753-1011
address: "1425 W. Lincoln Hwy, DeKalb, IL 60115"
email: cthurber@niu.edu
fontsize: 11pt
fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
#CJKmainfont: Noto Sans CJK JP # locally installed Asian character font, must use with xelatex
#github: github # github account
orcid: 0000-0002-3407-7589 # orcid identifier
#osf: ymqui # osf five character id
twitter:  # twitter handle
web: chesthurber.com
fontawesome: yes
nocite: '@*'
bibliography: 
  peer: peer_bib.bib
  other: other_bib.bib
validate-yaml: false
csl: apa-cv.csl
---

# Academic Appointments

**Northern Illinois University**

  - Associate Professor, Department of Political Science \hfill 2022-Present
  - Director of Undergraduate Studies, Deptartment of Political Science \hfill 2023 - Present
  - Assistant Professor, Department of Political Science \hfill 2016 - 2022

### University of Denver, Josef Korbel School of International Studies
- Visiting Scholar,  Sié Chéou-Kang Center for International Security \hfill 2022-2023

### University of Chicago
- Postdoctoral Scholar, Chicago Project on Security and Terrorism \hfill 2015-2016
     
### Harvard University, John F. Kennedy School of Government
- Research Fellow, Belfer Center for Science and International Affairs \hfill 2014-2015


# Education

### Tufts University, The Fletcher School of Law and Diplomacy
- Ph.D. | International Relations \hfill 2015

  - Dissertation: "Strategies of Violence and Nonviolence in Revolutionary Movements"
  - Committee: Richard Shultz, Zeynep Bulutgil, Erica Chenoweth
  - *Recipient of the Ackerman Award for Outstanding Doctoral Dissertation*
  
- M.A.L.D. | International Relations \hfill 2010

### Middlebury College
- B.A. | International Studies  (summa cum laude, Phi Beta Kappa) \hfill 2004

# Publications

### Book

- 2021. [*Between Mao and Gandhi: the Social Roots of Civil Resistance.*](\href{https://www.cambridge.org/core/books/between-mao-and-gandhi/21A630179930DC86E735BCA6F708D552) Cambridge University Press, Cambridge Studies in Contentious Politics. Reviewed in [*International Affairs*](https://doi.org/10.1093/ia/iiac031)  and [*Perspectives on Politics*](https://cup.org/42gBDBM).


### Journal Articles

  - Forthcoming. ["How Civil Resistance Improves Inclusive Democracy,"](https://www.researchgate.net/publication/375489313_How_Civil_Resistance_Improves_Inclusive_Democracy) with Subindra Bogati,  Titik Firawati, and Jonathan Pinckney. Forthcoming in *Perspectives on Politics.*

  - 2023. ["From Doctrine to Detonation: Ideology, Organization, and Terrorism in Mass Dissident Campaigns,"](https://doi.org/10.1177/00223433221135) with Margherita Belgioioso. *Journal of Peace Research*, OnlineFirst.

  - 2020. ["The Security Force Ethnicity (SFE) Project: Introducing a New Dataset,"](https://doi.org/10.1177/0738894217709012) with Paul Lorenzo Johnson. *Conflict Management and Peace Science* 37 (1): 106-129.

  - 2019. ["Social Ties and the Strategy of Civil Resistance. "](https://doi.org/10.1093/isq/sqz049) *International Studies Quarterly* 63 (4): 974-986.

  - 2018. ["Ethnic Barriers to Civil Resistance.](https://doi.org/10.1093/jogss/ogy018) *Journal of Global Security Studies* 3 (3): 255-270.

  - 2014. ["Militias as Sociopolitical Movements: Lessons from Iraq's Armed Shia Groups."](https://doi.org/10.1080/09592318.2014.945633) *Small Wars and Insurgencies* 25 (5-6): 900-923.

### Refereed Chapters & Reports

- Forthcoming. "A Yam Between Two Boulders: Global Orders, Regional Rivalries, and Contentious Politics," in Abu Bakarr Bah, ed. *Glocalized Security*, Forthcoming with Indiana University Press.

- 2021. [*From the Hills to the Streets to the Table: Civil Resistance and Peacebuilding in Nepal*](https://www.nonviolent-conflict.org/resource/from-the-hills-to-the-streets-to-the-table-rl/) with Subindra Bogati. ICNC Press.

### Policy Briefs & Essays

- 2022. ["Civil Resistance and Inclusive Democratization in Indonesia,"](https://www.csis.or.id/publications/civil-resistance-and-inclusive-democratization-in-indonesia) with Titik Firawati. Center for Strategic and International Studies, Jakarta. February 4, 2022.

- 2011. "From Coexistence to Cleansing: The Rise of Sectarian Violence in Baghdad, 2003-2006." \emph{al-Nakhlah: Journal of Southwest Asia and Islamic Civilization}.

- 2011. ["A Step Short of the Bomb: Explaining the Strategy of Nuclear Hedging."](https://jpia.princeton.edu/sites/jpia/files/jpia2011-2.pdf) \emph{Journal of Public and International Affairs} 22: 29-47.

### Book Reviews & Correspondence

- 2023. \href{https://doi.org/10.1017/S1537592722003693}{Reply to Corinna Jentzsch's Review} of \emph{Between Mao and Gandhi,} in \emph {Perspectives on Politics} 21 (1): 344 - 346.

- 2023. \href{https://doi.org/10.1017/S1537592722003693}{Review of \emph{Violent Resistance: Militia Formation and Civil War in Mozambique,} by Corinna Jentzsch (Cambridge, 2022),} in \emph {Perspectives on Politics} 21 (1): 344 - 346.
 
- 2014. Review of \emph{The Maoist Insurgency in Nepal: Revolution in the Twenty-First Century,} edited by Mahendra Lawoti and Anuk K. Pahari (Routledge, 2009), in \emph{Himalaya} 34, no. 1 (Spring): 148-150.


### Commentary

- 2024. \href{https://politicalviolenceataglance.org/2018/10/29/why-ethnic-cleavages-create-barriers-to-civil-resistance/}{"6+1 on \emph{Between Mao and Gandhi},"} \emph{The Duck of Minerva,} (February 29).

- 2018. \href{https://politicalviolenceataglance.org/2018/10/29/why-ethnic-cleavages-create-barriers-to-civil-resistance/}{"Why Ethnic Cleavages Create Barriers to Civil Resistance,"} \emph{Political Violence \@ a Glance,} (October 29).

- 2017. \href{https://politicalviolenceataglance.org/2017/09/11/mao-gandhi-and-the-choice-between-violent-and-nonviolent-action/}{"Mao, Gandhi, and the Choice Between Violent and Nonviolent Action,"} *Political Violence \@ a Glance* (September 11).

- 2017. \href{https://www.washingtonpost.com/news/monkey-cage/wp/2017/05/22/new-data-shows-a-sharp-increase-in-u-s-protest-activity-in-april/}{"New Data Shows a Sharp Increase in U.S. Protest Activity in April,"} with Erica Chenoweth, Jeremy Pressman, and Evan Perkoski, \emph{Washington Post,} "Monkey Cage" Blog (May 22)

- 2017. \href{https://www.washingtonpost.com/news/monkey-cage/wp/2017/04/24/in-trumps-america-whos-protesting-and-why-heres-our-march-report/}{"In Trump's America, Who's Protesting and Why?"} with Erica Chenoweth, David Prater, Jeremy Pressman, and Stephen Zunes, \emph{Washington Post,} "Monkey Cage" Blog (April 24).

### Work in Progress

  - "Ethnic Coalitions and the Trajectories of Resistance Campaigns," with Robert Tanner Bivens (Under Review).
  
  - "Military Ethnicity and Genocide," with Paul Lorenzo Johnson (Working Paper).
  
  - "Ethnicity and Defection during Uprisings from Below,"  with Paul Lorenzo Johnson, Theodore McLauchlin, and Julien Morency-Laflamme (Working Paper).
  
  - "A Nod, a Nudge, a Push, and a Putsch: Civil-Military Relations in the Heat of Mass Uprisings." (Working Paper).
  
  - "Cold War, Hot War, Color War: Popular Uprisings and Interstate Conflict," (Working Paper).

# Grants, Fellowships & Awards

### Externally Funded Research Grants

  - U.S. Institute of Peace: People Power, Peace Processes, and Democratization (2020-2021). \hfill $28,000
  - Smith Richardson Foundation: World Politics and Statecraft Fellowship (2014-2015). \hfill $7,500
  - Harvard Law School Program on Negotiation: Next Generation Grant (2013). \hfill $2,000
  
  
### Internally Funded Research Grants
  - Northern Illinois University: Great Journeys Grant (2020-2021). \hfill $15,000
  - Northern Illinois University: Great Journeys Grant (2017-2018). \hfill $14,000
  - Northern Illinois University: Summer Research and Artistry Grant (2017).  \hfill $13,500
  - Northern Illinois University: Student Engagement Fund Grant (2016-2017). \hfill $1,200
  - Tufts University: Fletcher Summer Research Grant (2014). \hfill $6,500
  - Tufts University: Fletcher Summer Research Grant (2013). \hfill $4,000

### Fellowships and Awards

  - Tobin Project: National Security Fellowship (2014).
  - Eisenhower Foundation: Clifford Roberts Fellowship (2012-2013).
  - Bradley Foundation: Dissertation Fellowship (2010-2011).
  - American Academy of Diplomacy: Leonard Marks Essay Contest Winner (2009).

# Invited Talks
  - University of Notre Dame, Liu Institute for Asia and Asian Studies (Scheduled November 2024).
  - University of Minnesota, Minnesota International Relations Colloquium (April 2024).
  - Centro de Investigacion y Docencia Economicas, Division of International Studies (May 2023, virtual).
  - International Foundation for Electoral Systems (May 2023, virtual).
  - Online Peace Science Colloquium [(April 2023, virtual).](https://www.youtube.com/watch?v=etW8WLcb1y4)
  - University of Denver, Korbel Research Seminar (February 2023).
  - University of Wisconsin-Madison, Comparative Politics Colloquium (February 2022).
  - Northwestern University, WCCIAS Global Lunchbox Series [(February 2022, podcast).](https://soundcloud.com/wccias/global-lunchbox-ches-thurber?utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing)
  - University of Chicago, Workshop on International Politics (January 2022, virtual).
  - International Center for Nonviolent Conflict (April 2021, December 2018, March 2017, virtual).
  - Alliance for Peacebuilding (April 2018, virtual)
  - Nepal Armed Police Force School, Kathmandu, Nepal (June 2016).
  - University of Chicago, Program on International Security Policy (May 2016).
  - University of Chicago, Comparative Politics Workshop (October 2015).
  - Harvard Kennedy School, Belfer International Security Program [(December 2014).](https://www.abc.net.au/listen/programs/bigideas/revolutionary-movements/6035042)
  - Tufts University, Fletcher Colloquium (October 2013).
  - Martin Chautari Invited Speaker Series, Kathmandu, Nepal (July 2013).


# Conference Papers
- "Mobilizing for Social Inclusion in Post-Conflict Nepal," with Subindra Bogati.
    - 2024. ISA Annual Meeting, San Francisco, CA.
    \vspace{1em}

- "India, China, and the Glocalization of Contention in Nepal."
    - 2023. Muslim Politics and World Society Symposium, Universitas Islam Internasional Indonesia (virtual). \vspace{1em}
    
- "Coalitions, Cleavages, and Claims: Rethinking the multiple dimensions of ethnicity in conflict," with Robert Tanner Bivens.
    - 2023. Four Corners Conflict Network Conference, Moab, UT.
    - 2023. ISA Annual Meeting, Montreal, CA.
    - 2021. ISA Annual Meeting, virtual format.
    \vspace{1em}
    
- "Inclusive Democratization in the Aftermath of Civil Resistance," with Subindra Bogati, Titik Firawati, and Jonathan Pinckney.
	 - 2022. ISA Annual Meeting (virtual).
	 - 2021. Conflict Research Society Annual Meeting (virtual).
	\vspace{1em}
	
- "A Nod, a Nudge, a Push, and a Putsch: Civ-Mil Relations in  Mass Uprisings."
  - 2021. APSA Annual Meeting (virtual).
  \vspace{1em}
  
- "Ethnicity and Defection during Uprisings from Below: New Data and Analysis," with Paul  Johnson, Theodore McLauchlin, and Julien Morency-LaFlamme.
	- 2021. ISA Annual Meeting, (virtual).
	- 2019. APSA Annual Meeting, Washington, DC.
	- 2019. ISA Annual Meeting, Toronto, ON.
	\vspace{1em}
	
- "Investigating Links between Ideology, Audiences, Fragmentation, 
		and Terrorism in Campaigns of Mass Resistance," with Margherita Belgioioso.
	- 2019. APSA Annual Meeting, Washington, DC.
	- 2019. ISA Annual Meeting, Toronto, ON.
	\vspace{1em}

- "The Ethnic Barrier to Nonviolent Action."
	- 2017. APSA Annual Meeting, San Francisco, CA.
	  \vspace{1em}
	  
- "Asymmetric Networks and the Breakdown of Civil Resistance: Evidence from Syria."
	- 2017. *Mobilization* Conference on Nonviolent Strategies and the State, San Diego, CA..
	- 2017. ISA Annual Meeting, Baltimore, MD.
  \vspace{1em}

- "Social Roots of Revolution: Gandhians, Maoists, and Insurgent Strategy in Nepal."
	- 2016. APSA Annual Meeting, Philadelphia, PA.
	- 2014. ISA Annual Meeting, Toronto, ON.
	\vspace{1em}
	
- "The Strategic Utility of Diversity in Violent and Nonviolent Conflict," with Ben Naimark-Rowse and Phoebe Donnelly.
	- 2016. ISA Annual Meeting, Atlanta, GA.
	 \vspace{1em}
	
- "Military Composition and Coups in the Modern Middle East," with Paul Lorenzo Johnson.
  - 2016. ISA Annual Meeting, Atlanta, GA.
	\vspace{1em}
	
- "Resistance Networks, Social Overlap, and Revolutionary Strategy." 
  - 2015. APSA Annual Meeting, San Francisco, CA.
  - 2015. MPSA Annual Meeting, Chicago, IL.
  - 2015. Harvard-MIT-Yale Political Violence Conference, Cambridge, MA.
  - 2015. ISA Annual Meeting, New Orleans, LA.
  \vspace{1em}

- "Stacking to Repress: The Effect of Ethnic Manipulation in the Military on State Violence," with Paul Lorenzo Johnson.
	 - 2015. MPSA Annual Meeting, Chicago, IL.
	 - 2015. ISA Annual Meeting, New Orleans, LA.
  \vspace{1em}
  
- "The Ethnic Composition of State Security Forces: Introducing a New Dataset," with Paul Lorenzo Johnson.
  - 2014. MPSA Annual Meeting, Chicago, IL.
  - 2014. ISA Annual Meeting, Toronto, ON.
  \vspace{1em}
  
- "Violence and Nonviolence in Revolutionary Movements."
  - 2013. ISA Annual Meeting, San Francisco, CA.
  - 2013. WPSA Annual Meeting, Hollywood, CA.		

# Other Conference Appearances

### Invited Workshops

- 2017. "What Do We Know About Networks of Resistance?," Peace Science Society Annual Meeting, Tempe, AZ.
- 2016. "Data and Measurement in Civil-Military Relations," Peace Science Society Annual Meeting, South Bend, IN.
- 2014. "Who Guards the Guardians? Leveraging New Data in Civil-Military Relations," Peace Science Society Annual Meeting, Philadelphia, PA.

### Roundtable Participant

- 2022. "Author Meets Critics: Ches Thurber's *Between Mao and Gandhi*," APSA Annual Meeting, Montreal, Canada.
- 2019. "Methods of Inquiry in the Study of Civil Resistance," ISA Annual Meeting, Toronto, Canada.

### Chair / Discussant
- 2024. "Disaggregating actors and institutions in protest dynamics,"  Discussant, ISA Annual Meeting, San Francisco, CA.
- 2023. Four Corners Conflict Network Conference, Discussant, Moab, UT.
- 2022. "Multi-Actor Approaches to the Study of Conflict," Discussant, ISA Annual Meeting, Montreal, Canada.
- 2022. "Civil-Military Relations, Security, and Society," Chair, ISA Annual Meeting, virtual format.
- 2021. "Social Organization in Regular and Irregular Armed Forces," Discussant, APSA Annual Meeting, virtual format.
- 2021. "New Research on Political Activism and Nonviolent Resistance,'' Discussant," MPSA Annual Meeting, virtual format.
- 2021. "Dynamics of Civil Resistance and Mass Contention," Discussant, ISA Annual Meeting, virtual format (April 2021).
- 2019. "Insurgency," Discussant, ISA Annual Meeting, Toronto, Canada.
- 2016. "Myanmar," Chair, Conference on Rebel Law and Governance, University of Chicago School of Law, Chicago, IL.
- 2016. "The Strategy of Nonviolence," Discussant, APSA Annual Meeting, Philadelphia, PA.
- 2016. "New Quantitative Research on Nonviolent Resistance," Discussant, ISA Annual Meeting, Atlanta, GA.
- 2015. "International Dimensions of Nationalist Politics,'' Discussant, Association for the Study of Nationalities, New York, NY.	  
 
# Teaching

### Northern Illinois University

*Undergraduate*

- Introduction to International Relations (Fall 2024, Sp. 2022, Fall 2017, Sp. 2017, Fall 2016).
- International Law and Organizations (Fall 2023, Fall 2021, Fall 2020, Fall 2018).
- International Security (Fall 2022, Sp. 2022, Sp.  2020, Sp. 2017, Sp. 2018).
- Topics in Contemporary Security (Fall 2023, Sum. 2022, Sp. 2021, Sp. 2018).

*Graduate*

- International Relations Theory (Fall 2017).
- International Security (Sp. 2024, Fall 2020, Sp. 2019).
- Introductory Analysis of Political Data (Fall 2021, Fall 2018).
- Intermediate Analysis of Political Data (Sp. 2021, Sp. 2019).
- Contentious Politics (Sp. 2022, Sp. 2020).

### Tufts University
- Theory and Practice of Nonviolent Resistance (Fall 2014).

### University of Alaska Fairbanks
- Intro to International Relations (Fall 2011, Fall 2012)
- Political Science Research Methods (Fall 2011, Fall 2012)
- Peace, War, and Security (Sp. 2012)
- Political Economy (Fall 2012, Sp. 2013)

# Teaching Recognition

- 2024. Outstanding Honors Faculty Spotlight, Northern Illinois University.
- 2023. Departmental Nominee, Excellence in Undergraduate Teaching Award, Northern Illinois University.
- 2018. Engaged Learning Exemplar, Northern Illinois University.
- 2012. College of Liberal Arts and Sciences Excellence in Teaching, University of Alaska Fairbanks.

# Advising

### Doctoral Dissertation Chair

- Annie Tong (in progress)
- Titik Firawati (2024), Gadjah Mada University
- Anna Zapolska (2022), U.S. Department of Justice
- Damir Kovacevic (2018), University of Wisconsin-Eau Claire
- Ilhan Aydemir (2018), Bolu Abant Izzet Baysal University
    
### Doctoral Dissertation Committee

- Salieg Munestri (in progress)
- Tanner Bivens (in progress)
- Rithiya Serrey (in progress)
- Jim Godowic (2021)
- James Boesen (2017) 
- Martin Claar (2017)
    
### M.A. Thesis Chair
- Rothsethamony Seng (2024)
- Janet Vallejo (2023)
- Mohammed Noor (2022)
- Nick Florian (2022)
- Peter Poterek (2020)
- Matthew Peerboom (2020)
- Dimitri Niforos (2018)

### M.A. Thesis Committee

- Thomas Mejdrech (in progress)
- Chibuzo Obasi (2023)
- Patricia Buczynski (2022)
- Tammie-Louise Finnegan (2022)
- Rithiya Serrey (2021)
- Sarwar Minar (2021)
- Medha Monjaury (2018)

### Undergraduate Honors Capstone

- Timothy Johnson (2019-2020)
- Quinn Carolan (2018)
  - Published in [*Compass: An Undergraduate Journal of American Political Ideas*](https://digitalcommons.jsu.edu/compass/vol5/iss1/1)

### Undergraduate Sponsored Research
- Shelby Emery (NIU Research Rookies, 2020-2021)
- Matthew Holt (NIU Student Engagement Research Grant, 2017)
- Kevin Kelly (Smith Richardson Foundation Grant, 2014-2015)
- Noah Cohen (Smith Richardson Foundation Grant, 2014-2015)
- Sarah Koosis (Smith Richardson Foundation Grant, 2014-2015)

### Undergraduate Independent Research
- Samm Cottone (2020)
- Thomas Phetmuengmay (2020)
- Sean Lehning (2019-2020)
  - Published in [*Compass: An Undergraduate Journal of American Political Ideas*](https://digitalcommons.jsu.edu/compass/vol5/iss1/2)
- Timothy Johnson (2019-2020)
- Zachary Tardio (2019)
- Quinn Carolan (2018)
- Jon Frejlich (2018)
- Matthew Peerboom (2017)

# Research and Pedagogy Training Workshops
- 2024. "Assessment Circle: Designing Good Learning Outcomes," NIU workshop, virtual format.
- 2022. "Developing a Positive Connection with Students with *Navigate*," NIU workshop, virtual format.
- 2022. "Designing an Accessible Course Syllabus," NIU workshop, virtual format.
- 2019. "Framing Feedback, NIU workshop," DeKalb, IL.
- 2018. "Engaged Learning, Teaching and Scholarship Conference," NIU, DeKalb, IL. 
- 2017. "Creating a More Inclusive Classroom," NIU workshop, DeKalb, IL.
- 2017. "Designing a Writing Infused Course," NIU workshop, DeKalb, IL.
- 2017. CFR College and University Educators' Workshop, New York, NY.
- 2016. "PI Academy," NIU Division of Research and Innovation Partnerships, DeKalb IL (2016-2017).
- 2012. Institute for Qualitative and Multi-method Research, Syracuse, NY.
- 2012. "iTeach Workshop," eLearning and Distance Education, Fairbanks, AK.

# Service

### Department
- Director of Undergraduate Studies (2023-Present)
- Committee on the Undergraduate Program (2016-2017, 2021-Present)
- NIU Model United Nations Team Faculty Advisor (2016-Present)
- Personnel Committee (2024)
- Department Chair Search Committee (2019, 2020)
- Committee on the Graduate Program (2016-2017)


### University
- CLAS Curriculum Committee (2024-Present)
- Honors Program Committee (2020-Present)
- NNGO Steering Committee (2023-Present)
- Dissertation Completion Fellowship Selection Committee (2021)

### State
- Illinois Articulation Initiative, Political Science Panel Member (2023-Present)

### Editorial Board
- African Conflict and Peacebuilding Review (2022-Present).

### Reviewer

- *Journals:* American Political Science Review, British Journal of Political Science, Comparative Political Studies, Comparative Politics, Conflict Management and Peace Science, European Journal of International Relations, Global Security and Intelligence Studies, International Area Studies Review, International Security, International Social Science Journal, International Studies Quarterly, Journal of Conflict Resolution, Journal of Global Security Studies, Journal of Peace Research, Journal of Politics, Middle Eastern Studies, Mobilization, Perspectives on Politics, PLOS ONE, Research and Politics,  Security Studies.
    
- *Grants:* Harry Frank Guggenheim Foundation, Israel Science Foundation, National Science Center (Poland) 

- *Presses:* Columbia University Press, ICNC Press, Routledge
 
### External Examiner
- University of Otago (Ph.D.)
- Swarthmore College (B.A. Honors)

# Media Appearances

### Television
- *WIFR 23 Rockford*: [Feb. 24, 2023](https://www.wifr.com/2023/02/24/world-marks-one-year-since-russia-invaded-ukraine/); [Aug. 16, 2021](https://www.wifr.com/content/news/LOCAL-PROFESSORS-WEIGH-IN-ON-MISSILE-STRIKE--566827601.html); Jan. 8, 2020.
- *WREX Rockford*: Feb. 25, 2022.
- *Fox 32 Chicago*: [April 21, 2022](https://www.fox32chicago.com/video/1060344); [Feb. 23, 2022](https://www.fox32chicago.com/video/1038416); [Feb. 16, 2022](https://www.youtube.com/watch?v=h_ESpwI6_rc); Sept. 5, 2021; Aug. 31, 2021; [June 16, 2021](https://www.fox32chicago.com/video/944837).
- *WGN 9 Chicago*: [Aug. 16, 2021](https://www.youtube.com/watch?v=IsijwhsA4Nk).
-*WTVO Rockford*: [Aug. 16, 2021](https://www.mystateline.com/news/local-news/rockford-veteran-worries-for-afghan-allies-left-behind-as-taliban-overrun-the-country/)

### Radio

- *NPR*, "The 21st": [Feb. 28, 2022](https://www.npr.org/podcasts/475680317/the-21st).
- *WNIJ Northern Public Radio*: [Feb. 24, 2022](https://www.northernpublicradio.org/2022-02-24/dekalb-county-this-week-reaction-to-tensions-in-europe-stage-coach-players-to-hold-auditions); [Aug. 28, 2020](https://www.northernpublicradio.org/business/2020-08-28/tiktok-data-security-and-dueling-economies); [April 13, 2017](https://www.northernpublicradio.org/post/scrutiny-mounts-travel-orders); [April 7, 2017](https://www.northernpublicradio.org/post/niu-professor-trump-drew-line-chemical-weapons).
- *WBBM-AM Chicago*: Aug. 16, 2021.
- *WCEV 1450 Chicago*, "Radio Islam": [Feb. 19, 2019](https://soundcloud.com/radioislamusa/ep-6721-crisis-in-venezuela-02-19-2019); [May 4, 2018](https://soundcloud.com/radioislamusa/ep-527-conflict-in-a-nuclear-world-with-ches-thurber-5318); [Feb. 15, 2018](https://www.radioislam.com/node/28279).
- *Australian Broadcast Corporation*, "Big Ideas": [Feb. 18, 2015](https://www.abc.net.au/radionational/programs/bigideas/revolutionary-movements/6035042).

### Print

- *The DeKalb Daily Chronicle*: [August 20, 2021](https://www.shawlocal.com/daily-chronicle/news/local/2021/08/21/history-repeating-itself-local-veterans-residents-reflect-on-events-in-afghanistan/)
- *Egypt Today*: [Sept. 14, 2017](https://www.egypttoday.com/Article/2/22724/Iraqi-Militias-The-Tangle-of-Flags)
- *The Fletcher Security Review*: [February 2017](https://docs.wixstatic.com/ugd/c28a64_c8ed8f4140894077be782bda046b4f96.pdf)

# Public Talks & Engagement

- Roundtable on "Indonesia's Presidential Election," (Organizer and Moderator) Northern Illinois University, DeKalb, IL (February 2024).

- Roundtable on "The War in Gaza," (Organizer and Panelist) Northern Illinois University, DeKalb, IL (October 2023).

- Roundtable on "The War in Ukraine," Northern Illinois University, DeKalb, IL (March 2022).

- Roundtable on "Reflections on September 11, 2001," Northern Illinois University, DeKalb, IL (September 2021).

- "What Gandhi Can Teach Us About Political Organizing," NIU Lifelong Learning Institute, DeKalb, IL (January 2021).

- "The Power of Nonviolence in Global Politics," NIU Lifelong Learning Institute, DeKalb, IL (October 2017).

- "Sadr, SCIRI, Scary? Iraq's Armed Shia Groups," Women in International Security, Fletcher Chapter, Medford, MA (February, 2010).	

# Research and Policy Consulting

- **National Democratic Institute**, Democracy Assistance in Transition \hfill Washington, DC (2023-2024)
  - Served on Democracy Assistance in transition advisory group; prepared report on social inclusion in the aftermath of democratic transitions.
\vspace{1em}

- **UNESCWA**, Restoring Syria's Social Fabric \hfill Beirut, Lebanon (2020)
  - Presented research findings from book in Beirut, Lebanon to inform UN report on preparing for the aftermath of civil war in Syria.
\vspace{1em}

- **University of Denver**, Innovations in Peacebuilding \hfill Denver, CO (2016)
  - Conducted interview-based field research in Nepal and prepared report  on the impact of international actors on human rights in post-war Nepal.
\vspace{1em}

- **The Atlantic Council**, The Future of Authoritarianism Project \hfill Washington D.C. (2015)
  - Conducted interviews with policymakers and activists to write three book chapters on U.S. support for protest movements in Central Asia.
\vspace{1em}

- **The Fletcher School/MIT Lincoln Laboratories**, Space Policy Working Group \hfill Medford, MA (2010-2011)
  - Developed presentations for client on space governance policies.

# Professional Policy Experience

- **U.S. Embassy Doha**, Public Affairs Intern \hfill Doha, Qatar (2009)
	- Drafted op-eds, speeches, and press releases pertaining to human rights, democracy, and interfaith dialogue. Organized cultural exchange events.
\vspace{1em}

- **Office of Rep. Peter Welch**,  Legislative Assistant \hfill Washington, DC (2007-2008)
	- Advised and drafted legislation on international, military, taxation, and financial services policy.
\vspace{1em}

- **Vermont State Senate**, Aide to the Senate President Pro Tempore \hfill Montpelier, VT (2006)
	- Managed policy advice, scheduling, and correspondence for Senate Leader.
\vspace{1em}

- **Vermont Medical Society**, Policy Analyst \hfill Montpelier, VT (2005)
	- Prepared policy analysis of federal Medicare Part D expansion, state Medicaid reform proposals, and mental health policies.
\vspace{1em}

- **United Parcel Service**, Legislative Assistant \hfill Washington, DC (2004-2005)
	- Assisted federal lobbying team with analysis of international trade agreements as well as federal and state transportation policies.



