on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: quarto-ext-chk


jobs:
  quarto-ext-chk:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-pandoc@v2
        with: 
          pandoc-version: "3.1.8"
      
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: template.qmd

